services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/christmas_messages_dc
      SPRING_DATASOURCE_USERNAME:
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: christmas_messages_dc
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5433:5432"
