spring:
  application:
    name: christmas-tree
  datasource:
    url: jdbc:postgresql://localhost:5432/lc_party_planner
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
